# Generated by Django 4.2.2 on 2023-10-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionName', models.CharField(max_length=255)),
                ('collectionImage', models.ImageField(upload_to='collections')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockName', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('offerImage', models.ImageField(upload_to='homeBlock')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('isMobile', models.BooleanField(default=False)),
                ('slide', models.ImageField(upload_to='slider')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productDesc', models.TextField()),
                ('productPrice', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='products')),
                ('primary', models.ImageField(upload_to='primary')),
                ('secondary', models.ImageField(upload_to='secondry')),
                ('tertiary', models.ImageField(upload_to='tertiary')),
                ('tags', models.TextField(blank=True, null=True)),
                ('is_in_Offer', models.BooleanField(default=False)),
                ('offerPrice', models.IntegerField(blank=True, null=True)),
                ('offerName', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('dateUploaded', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
                ('collections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collections')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
        ),
    ]
