# Generated by Django 4.2.2 on 2023-06-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('isMobile', models.BooleanField(default=False)),
                ('slide', models.ImageField(upload_to='media/slider')),
            ],
        ),
    ]
