# Generated by Django 4.2.2 on 2023-06-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockName', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('offerImage', models.ImageField(upload_to='media/homeBlock')),
            ],
        ),
    ]
