# Generated by Django 4.2.2 on 2023-06-10 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categories_alter_homeblock_offerimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='dateUploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
