# Generated by Django 4.2.2 on 2023-06-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gender_products_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
